
name: Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: mkdir public && touch public/index2.html
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
